// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import { validateEmail } from './Login';

describe('Email Validation', () => {
  test('returns true when email is valid', () => {
    expect(validateEmail('test@example.com')).toBe(true);
  });

  test('returns false when email is invalid', () => {
    expect(validateEmail('invalidemail')).toBe(false);
  });

  test('returns false when email is missing "@" symbol', () => {
    expect(validateEmail('testexample.com')).toBe(false);
  });

  test('returns false when email is missing domain', () => {
    expect(validateEmail('test@')).toBe(false);
  });

  test('returns false when email is missing username', () => {
    expect(validateEmail('@example.com')).toBe(false);
  });

  test('returns false when email is null', () => {
    expect(validateEmail(null)).toBe(false);
  });

  test('returns false when email is undefined', () => {
    expect(validateEmail(undefined)).toBe(false);
  });
});
