// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import { validateEmail } from './Login';

describe("Email Validation", () => {
  test("validates correct email", () => {
    const email = "test@gmail.com";
    expect(validateEmail(email)).toBe(true);
  });

  test("returns false for incorrect email", () => {
    const email = "testgmail.com";
    expect(validateEmail(email)).toBe(false);
  });

  test("returns false for email without domain", () => {
    const email = "test@";
    expect(validateEmail(email)).toBe(false);
  });

  test("returns false for email without @ symbol", () => {
    const email = "test.com";
    expect(validateEmail(email)).toBe(false);
  });
});
