// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import { validateEmail } from "./Login";

describe("Email Validation", () => {
  test('validateEmail returns true for valid email', () => {
    expect(validateEmail('test@example.com')).toBeTruthy();
  });

  test('validateEmail returns false for invalid email', () => {
    expect(validateEmail('test@.com')).toBeFalsy();
  });

  test('validateEmail returns false for email without domain', () => {
    expect(validateEmail('test@')).toBeFalsy();
  });

  test('validateEmail returns false for email without @ symbol', () => {
    expect(validateEmail('test.com')).toBeFalsy();
  });

  test('validateEmail returns false for email with spaces', () => {
    expect(validateEmail('test @example.com')).toBeFalsy();
  });

  test('validateEmail returns false for empty string', () => {
    expect(validateEmail('')).toBeFalsy();
  });
});
