// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import React from "react";
import { render, fireEvent, cleanup } from "@testing-library/react";
import { Login } from "./Login.js";

describe("Login Component", () => {
  let getByTestId;

  afterEach(cleanup);

  beforeEach(() => {
    ({ getByTestId } = render(<Login />));
  });

  test("Email is not valid", () => {
    const emailInput = getByTestId("formBasicEmail");
    fireEvent.change(emailInput, { target: { value: "invalidEmail" } });

    const submitButton = getByTestId("submit");
    fireEvent.click(submitButton);

    const errorAlert = getByTestId("error");
    expect(errorAlert).toHaveTextContent("Email is not valid");
  });

  test("Email is valid", () => {
    const emailInput = getByTestId("formBasicEmail");
    fireEvent.change(emailInput, { target: { value: "valid@email.com" } });

    const submitButton = getByTestId("submit");
    fireEvent.click(submitButton);

    const userAlert = getByTestId("user");
    expect(userAlert).toHaveTextContent("valid@email.com");
  });

  test("Reset form", () => {
    const emailInput = getByTestId("formBasicEmail");
    fireEvent.change(emailInput, { target: { value: "valid@email.com" } });

    const passwordInput = getByTestId("formBasicPassword");
    fireEvent.change(passwordInput, { target: { value: "password" } });

    const resetButton = getByTestId("reset");
    fireEvent.click(resetButton);

    expect(emailInput.value).toBe("");
    expect(passwordInput.value).toBe("");
  });
});
