// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import React from "react";
import { render } from "@testing-library/react";
import App from "./App";
import Login from "./components/Login";

describe("App Component", () => {
  let wrapper;

  beforeEach(() => {
    wrapper = render(<App />);
  });

  test("renders without crashing", () => {
    expect(wrapper).not.toBeNull();
  });

  test("renders the heading", () => {
    const { getByText } = wrapper;
    const headingElement = getByText(/This is React Testing Tutorial/i);
    expect(headingElement).toBeInTheDocument();
  });

  test("renders the Login component", () => {
    const { getByTestId } = wrapper;
    const loginElement = getByTestId("child");
    expect(loginElement).toBeInTheDocument();
  });
});
