// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import React from "react";
import { render } from "@testing-library/react";
import App from "./App";

describe("App", () => {
  let component;

  beforeEach(() => {
    component = render(<App />);
  });

  test("renders without crashing", () => {
    expect(component).toBeTruthy();
  });

  test("renders heading", () => {
    const { getByText } = component;
    const heading = getByText(/This is React Testing Tutorial/i);
    expect(heading).toBeInTheDocument();
  });

  test("renders Login component", () => {
    const { getByTestId } = component;
    const loginComponent = getByTestId("child");
    expect(loginComponent).toBeInTheDocument();
  });
});
