// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";
import "@testing-library/jest-dom";

describe('Testing afterAll function', () => {
    let originalError;
    
    beforeAll(() => {
        originalError = console.error;
        console.error = jest.fn();
    });

    test('Check if console.error is mocked', () => {
        console.error('This is a test error');
        expect(console.error).toHaveBeenCalled();
    });

    test('Check if console.error is not called', () => {
        expect(console.error).not.toHaveBeenCalled();
    });

    afterAll(() => {
        console.error = originalError;
    });

    test('Check if console.error is restored', () => {
        console.error('This is a test error');
        expect(console.error).not.toHaveBeenCalled();
    });
});
