// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";
import "@testing-library/jest-dom";

describe('afterAll function test suite', () => {
  let originalError;

  beforeAll(() => {
    originalError = console.error;
  });

  test('should restore original console.error after all tests', () => {
    console.error = jest.fn();
    expect(console.error).not.toBe(originalError);
    
    afterAll(() => {
      console.error = originalError;
    });
    expect(console.error).toBe(originalError);
  });

  test('should not change console.error if it was not modified', () => {
    const initialConsoleError = console.error;
    
    afterAll(() => {
      console.error = originalError;
    });
    
    expect(console.error).toBe(initialConsoleError);
  });
});
