// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";
import "@testing-library/jest-dom";

// Assuming we have the originalError defined somewhere in our code
let originalError;

describe('afterAll method', () => {
  let consoleOutput = [];
  const originalLog = console.error;

  beforeEach(() => {
    consoleOutput = [];
    console.error = (message) => consoleOutput.push(message);
  });

  afterAll(() => {
    console.error = originalError;
  });

  test('console.error is restored to originalError after all tests', () => {
    console.error('This is a test error message');
    expect(consoleOutput).toEqual(['This is a test error message']);
  });

  test('console.error is not the original error function during tests', () => {
    expect(console.error).not.toBe(originalLog);
  });

  test('console.error is the original error function after all tests', () => {
    expect(console.error).toBe(originalError);
  });
});
