// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";
import "@testing-library/jest-dom";

let originalError;

describe('Test for console.error method', () => {
  beforeAll(() => {
    originalError = console.error;
  });

  beforeEach(() => {
    console.error = (...args) => {
      if (/Warning: ReactDOM.render is no longer supported in React 18./.test(args[0])) {
        return;
      }
      originalError.call(console, ...args);
    };
  });

  afterAll(() => {
    console.error = originalError;
  });

  test('Warns when ReactDOM.render is no longer supported', () => {
    const consoleSpy = jest.spyOn(console, 'error');

    console.error('Warning: ReactDOM.render is no longer supported in React 18.');
    expect(consoleSpy).not.toHaveBeenCalled();

    consoleSpy.mockRestore();
  });

  test('Does not warn when error is not about ReactDOM.render', () => {
    const consoleSpy = jest.spyOn(console, 'error');

    console.error('Random error');
    expect(consoleSpy).toHaveBeenCalled();

    consoleSpy.mockRestore();
  });
});
