// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";
import "@testing-library/jest-dom";

describe('console error override', () => {
    let originalError;

    beforeAll(() => {
        originalError = console.error;

        console.error = (...args) => {
            if (/Warning: ReactDOM.render is no longer supported in React 18./.test(args[0])) {
                return;
            }
            originalError.call(console, ...args);
        };
    })

    afterAll(() => {
        console.error = originalError;
    });

    test('should not call the original console.error for React 18 warning', () => {
        const mockError = jest.fn();
        console.error = mockError;

        console.error('Warning: ReactDOM.render is no longer supported in React 18.');
        expect(mockError).not.toHaveBeenCalled();
    });

    test('should call the original console.error for other messages', () => {
        const mockError = jest.fn();
        console.error = mockError;

        console.error('An error occurred');
        expect(mockError).toHaveBeenCalledWith('An error occurred');
    });
});
