// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

const reportWebVitals = require('./reportWebVitals');

describe('reportWebVitals', () => {
  let onPerfEntry;

  beforeEach(() => {
    onPerfEntry = jest.fn();
  });

  afterEach(() => {
    jest.resetAllMocks();
  });

  test('should not call onPerfEntry if it is not a function', () => {
    reportWebVitals(null);
    expect(onPerfEntry).not.toHaveBeenCalled();
  });

  test('should call onPerfEntry if it is a function', () => {
    reportWebVitals(onPerfEntry);
    setImmediate(() => {
      // Assuming import('web-vitals') resolves immediately
      expect(onPerfEntry).toHaveBeenCalled();
    });
  });

  test('should call onPerfEntry with correct arguments', () => {
    reportWebVitals(onPerfEntry);
    setImmediate(() => {
      // Assuming import('web-vitals') resolves immediately
      expect(onPerfEntry).toHaveBeenCalledWith(expect.anything());
    });
  });
});
