// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

const reportWebVitals = require('./reportWebVitals');

describe('reportWebVitals', () => {
  let onPerfEntry;

  beforeEach(() => {
    onPerfEntry = jest.fn();
    jest.mock('web-vitals', () => ({
      getCLS: jest.fn().mockImplementation(cb => cb()),
      getFID: jest.fn().mockImplementation(cb => cb()),
      getFCP: jest.fn().mockImplementation(cb => cb()),
      getLCP: jest.fn().mockImplementation(cb => cb()),
      getTTFB: jest.fn().mockImplementation(cb => cb()),
    }));
  });

  afterEach(() => {
    jest.resetModules();
  });

  test('should not call onPerfEntry if it is not a function', () => {
    reportWebVitals(null);
    expect(onPerfEntry).not.toHaveBeenCalled();
  });

  test('should call onPerfEntry if it is a function', async () => {
    await reportWebVitals(onPerfEntry);
    expect(onPerfEntry).toHaveBeenCalled();
  });

  test('should call onPerfEntry for each web vital', async () => {
    await reportWebVitals(onPerfEntry);
    expect(onPerfEntry).toHaveBeenCalledTimes(5);
  });
});
