// Test generated by RoostGPT for test springMongoDB using AI Type Open AI and AI Model gpt-4

const reportWebVitals = require('./reportWebVitals');

describe('reportWebVitals', () => {

  // Mock the web-vitals module
  jest.mock('web-vitals', () => ({
    getCLS: jest.fn(),
    getFID: jest.fn(),
    getFCP: jest.fn(),
    getLCP: jest.fn(),
    getTTFB: jest.fn()
  }));

  const vitals = require('web-vitals');

  beforeEach(() => {
    vitals.getCLS.mockClear();
    vitals.getFID.mockClear();
    vitals.getFCP.mockClear();
    vitals.getLCP.mockClear();
    vitals.getTTFB.mockClear();
  });

  test('should do nothing if onPerfEntry is not a function', () => {
    reportWebVitals(null);
    expect(vitals.getCLS).not.toBeCalled();
    expect(vitals.getFID).not.toBeCalled();
    expect(vitals.getFCP).not.toBeCalled();
    expect(vitals.getLCP).not.toBeCalled();
    expect(vitals.getTTFB).not.toBeCalled();
  });

  test('should call all web-vitals functions if onPerfEntry is a function', () => {
    const onPerfEntry = jest.fn();
    reportWebVitals(onPerfEntry);
    expect(vitals.getCLS).toBeCalledWith(onPerfEntry);
    expect(vitals.getFID).toBeCalledWith(onPerfEntry);
    expect(vitals.getFCP).toBeCalledWith(onPerfEntry);
    expect(vitals.getLCP).toBeCalledWith(onPerfEntry);
    expect(vitals.getTTFB).toBeCalledWith(onPerfEntry);
  });

});
